spruceid/kepler

.github/workflows/rust.yml, .gitmodules, Cargo.toml
checks out Rocket in CI to resolve a multiple-artifacts build issue (as rocket_cors also uses a git dependancy for Rocket)
=> checkout rocket for building vendored

Cargo.lock, Cargo.toml, src/auth.rs, src/cas.rs, src/codec.rs, src/ipfs.rs, src/main.rs, src/orbit.rs, src/tz.rs
Adds functionality for creating an orbit by POSTing content to `/`. Request contents are the same as putting content into an orbit except that the authorization header contains information used to generate the orbit ID.
Orbit IDs are generated using a domain secret, a nonce and the public key hash of the administrator in the form of a CID, made over the string `pkh:domain:nonce` with the `raw` codec.
Additionally, this PR refactors authorization into a set of related traits, AuthorizationPolicy and AuthorizationToken, as well as adds an Orbit trait with a simple implementation (mostly stubbed right now).
Orbits exist on disk in a directory specified by the `ROCKET_DB_PATH` environment variable at start time.
For Batch insertion on Orbit creation to work, PR #16 must be merged.
Currently …
=> orbit creation

src/main.rs, src/orbit.rs, src/tz.rs
uses `base58check` as the default string encoding for CIDs and OIDs
=> use base58check for CID string representations

src/auth.rs, src/main.rs, src/orbit.rs, src/tz.rs
implements verification according to the OID generation procedure discussed in #12
=> update OID input

src/main.rs
`load_orbits` would attempt to use the file name instead of file path for loading the databases. This PR fixes that.
=> load using file path instead of file name

Cargo.lock, src/main.rs, src/orbit.rs
Previously, the tz-form uri used for Orbit ID generation was `tz:<address>?<query-params>`. This PR updates this URIs to be of the form `tz;address=<address>;<matrix-params>`, where `<address>` is now a required matrix-param for tz-derived Orbit IDs. This is desirable as `tz:<address>` is not a path segment that can appear in valid URIs. Matrix params are chosen over query params to support params in kepler URIs of the form: `kepler://tz;<params>/<content-id>`, as query params may only occur in the final segment of a URI.
=> tz address as Oid param

Cargo.lock, Cargo.toml, src/auth.rs, src/cas.rs, src/ipfs.rs, src/main.rs, src/orbit.rs, src/tz.rs
Adds a `List` operation, which will return a list of all CIDs in the orbit which are pinned/aliased. For DAG structures, this means only the head of the DAG will be returned. The format of the request is a `GET` request on the orbit ID path, i.e. `GET https://<host_url>/<orbit_id>`.
=> List orbit contents

src/orbit.rs
each IPFS node listening on port `0` would cause the next to fail, leaving only one orbit existing at any one time. Currently there is no need to listen, this was left over from when `ipfs-embed` required a listen call to set `network.enabled` to true and allow it to work.
=> dont listen with ipfs nodes

Cargo.lock, Cargo.toml, src/orbit.rs
cleans up some mixed dependancies:
- remove `libp2p_core` as a direct dependancy
- update `libipld`
- use crates.io-published `ipfs_embed` instead of a git link
=> use released ipfs_embed over git link

Cargo.lock, Cargo.toml, src/auth.rs, src/config.rs, src/lib.rs, src/orbit.rs, src/routes.rs, src/tz.rs
Whilst adding caching to implement the on-demand loading of orbits, the current types/traits showed to be too interlinked for a more hierarchical/abstracted code structure.
This PR is a proposal and doesn't yet compile. Amongst the changes:
- the authentication goes through the orbit (one consequence is that we can directly give the orbit to the requests handlers); 
- I have removed cyclical dependent types and some inner types with the idea that most linked types only have one combination possible (e.g. a Tezos policy will only accept a Tezos token) meaning we will probably only need hierarchies of enums; and
- I added caching using `cached`.
=> On-demand (cached) loading and decouple types

kepler.toml, src/allow_list.rs, src/config.rs, src/lib.rs, src/routes.rs
Set `public_get = true` in `kepler.toml` or set env var `KEPLER_PUBLIC_GET=true` to serve GET requests without authorization.
=> add a config entry for allowing public GET requests

src/s3_routes.rs
- the get/list methods had the same rank.
- the no_auth list method had a lower rank than get, so Kepler would treat a list as a get with an empty key
=> Fix issues with the s3 routes.

src/orbit.rs
By removing the time-based cache eviction, the error described in spruceid/kepler#67 can only occur if more than 100 orbits (configurable) are created.
=> fix/sqlite-lock-workaround - remove time-based cache eviction.

src/relay.rs, src/s3/entries.rs, src/s3/mod.rs, src/tz.rs
This is a somewhat trivial PR but it fixes all of the warnings yielded by `cargo clippy --tests`.
=> Fix clippy warnings in tests

Cargo.lock, Cargo.toml, src/lib.rs, src/orbit.rs, src/s3/entries.rs, src/siwe.rs, src/zcap.rs
Implements resource access authorization (delegation and invocation) using EIP-4361 Sign In With Ethereum. Clients can delegate and invoke capabilities via encoding them as resource URIs in a SIWE message. SIWE and ZCAP messages can be used together in delegation chains (e.g. a ZCAP delegation and a SIWE invocation, and vice versa). This implementation contains much complexity that would be better abstracted/refactored in future, as the different combinations are implemented "manually".
=> Sign In With Ethereum support

Cargo.lock, Cargo.toml, src/allow_list.rs, src/auth.rs, src/ipfs.rs, src/lib.rs, src/orbit.rs, src/relay.rs, src/routes/core.rs, src/routes/s3.rs, src/s3/behaviour.rs, src/s3/entries.rs, src/s3/mod.rs, src/s3/store.rs, src/siwe.rs, src/transport.rs, src/tz_orbit.rs, src/zcap.rs
As above. This is based on the `kepler-staging` branch of `spruceid/rust-ipfs`, which contains a number of changes and fixes to rust-ipfs to make it usable by Kepler.
Outstanding issues (which may not be addressed by this PR):
- Replication: currently there is a race condition with connecting to a peer and then immediately writing data. There will also be further work to support peer authentication for mutable orbits.
- Garbage collection: unpinned blocks are not removed. We will need to either extend the object deletion process to clean down recursively, or else write a GC'er. This may make more sense to look into as we think more about storage backends.
=> Switch out ipfs-embed for rust-ipfs.

src/lib.rs, src/orbit.rs, src/siwe.rs
- Rocket state needed updated Keypair type.
- Needed to connect to the relay from new peers immediately otherwise the S3 service setup failed.
- Needed to compare the CIDs by value from delegation and invocation, since the CIDs were being formatted as strings with different multibases.
=> Fix outstanding bugs from ipfs cutover.

src/s3/behaviour.rs
There are optional functions on the trait that are equivalent to those that were removed. In the long term we might want to make more use of the ConnectionHandler, but I need to spend more time understanding exactly what that is for.
=> Fix KV behaviour.

src/auth.rs, src/ipfs.rs, src/siwe.rs, src/zcap.rs
The updated `impl AuthorisationPolicy<...>` resource checking from PR #83 was not checking that the invoked resource action was the same as the delegated resource action. This pr should correct that. This PR also fixes `Ipfs::list`, returning directly pinned blocks.
=> Fix target action checking against capability and Ipfs list fn

src/auth.rs
Delegated orbit creation was failing when checking the invoked resource against the capabilities. The resource: `kepler:ens:example.eth://default#peer` does not have a path, but is a valid capability. Therefore a capability with an empty path should also allow invocations against an empty path.
=> Fix delegated orbit creation.

.github/workflows/docker.yml
It only takes 20min https://github.com/spruceid/kepler/runs/5852970615?check_suite_focus=true :grimacing: 
I'm not really keen on adding caching for releases. But it's easy to enable, so if we add e2e that use the docker image, we can.
=> Add Docker CI

src/storage/mod.rs
Fix incorrect cid string and use create_dir_all to easily ignore errors about dir already existing.
=> Fix orbit creation.

Cargo.lock, Cargo.toml, src/auth.rs, src/config.rs, src/kv/entries.rs, src/kv/mod.rs, src/kv/store.rs, src/lib.rs, src/main.rs, src/relay.rs, src/routes/mod.rs, src/siwe.rs, src/storage/mod.rs, src/tracing.rs
Basic Jaeger implementation. It doesn't support propagation, behaves as a compactor instead of being able to rely on an agent, and only instruments the invoke endpoint. Things will evolve as `tracing` 0.2 comes out and the OpenTelemetry standardisation converges, and as Rocket gets native tracing support (or whether we move to Axum).
Also adds support for JSON formatted logs.
Here's an example trace:
This example was run with Tempo, and here is the cargo command:
```
RUST_LOG=info KEPLER_LOG_FORMAT=Json KEPLER_LOG_TRACING_ENABLED=true OTEL_EXPORTER_JAEGER_ENDPOINT="http://127.0.0.1:14268/api/traces?format=jaeger.thrift" cargo run
```
Also updated to Rust 2021 and Rocket `0.5.0-rc.2`.
=> Initial tracing support

src/routes/mod.rs
Fix #120 by adding an extra `InvocationResponse` case representing not-found. existing `Empty` case results in a `200` success response
=> distinguish between empty 200 response and 404 not found

lib/src/authorization.rs
Currently get the following error when making an invocation with a JWK generated outside of the SDK:
```'failed to generate proof for invocation: Unsupported algorithm'```
`JWK::generate_ed25519` for example does not populate the `alg` field in the generated JWK, but `JWK::get_algorithm` will return the correct algorithm for some curves.
=> Fix jwk algorithm for invocations.

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, Dockerfile, kepler.toml, lib/src/resolver.rs, lib/src/resource.rs, sdk/src/serde_siwe.rs, sdk/src/session.rs, sdk/src/siwe_utils.rs, sdk/src/util.rs, src/authorization.rs, src/indexes/heads.rs, src/kv/store.rs, src/routes/mod.rs, src/storage/indexes.rs, src/storage/utils.rs, src/tracing.rs
Docker builds have been broken by the [rate limiting of `protoc`](https://github.com/libp2p/rust-libp2p/pull/3199) builds from the Github api stemming from it's (unavoidable) use in libp2p, as well as some other issues. This PR swaps to a branch of libp2p which removes the dependancy on `protoc` in favour of a pure rust impl. This is not a perfect fix, once the [corresponding libp2p PR](https://github.com/libp2p/rust-libp2p/pull/3066) is merged this branch will disappear and another PR will be needed to go back to libp2p trunk. Another option is to fully remove libp2p for now, but this would entail a number of breaking changes.
=> fix docker container

kepler.toml, src/config.rs, src/lib.rs
Clients running within the browser have been unable to inspect the headers of responses from Kepler. The headers are present, but the [CORS header `Access-Control-Expose-Headers`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers) was not set, preventing browser scripts from accessing them. This left only the `content-type` header available for clients running in the browser. This PR adds the aforementioned CORS header to allow clients to see the response headers. It is configurable with the `cors` config option, either `true` or `false`. I tried to make it more granular with all the cors options but it couldn't solve lifetime issues quickly enough.
(Please delete options that are not relevant)  
Browser version(s):  All except safari
SDK version(s): …
=> expose headers

src/config.rs, src/kv/store.rs, src/routes/mod.rs, src/storage/either.rs, src/storage/file_system.rs, src/storage/mod.rs, src/storage/s3.rs
Currently we cannot easily find the size of an entry in an ImmutableStore. This PR wraps responses from the store in a Content struct which holds the length and can be expanded with additional useful fields in the future. This assists with setting the content-length on responses and will be useful for p2p communication when exchanging stored contents.
=> Content length from store

Cargo.lock, lib/Cargo.toml, lib/src/lib.rs, sdk-wasm/Cargo.toml, sdk-wasm/src/lib.rs, sdk/src/session.rs, sdk/src/siwe_utils.rs, src/authorization.rs
This PR updates the dependencies in Kepler to fix upstream builds in ssx-rs. SSI is updated to 0.5 and capgrok is upadted to use the siwe-recap package.
=> Update Kepler SDK Dependencies

sdk/src/session.rs, src/kv/store.rs
Currently the invocation expiry time is calculated to be (in unix seconds) 60 + the nanosecond offset of `now`. This is incorrect, it should be `now` + 60. This PR fixes it
=> Fix invocation expiry time

Cargo.lock, Cargo.toml, README.md, kepler-core/Cargo.toml, kepler-core/src/db.rs, kepler-core/src/keys.rs, kepler-core/src/lib.rs, kepler.toml, src/auth_guards.rs, src/config.rs, src/lib.rs, src/routes/mod.rs
This PR moves the host key management into the `OrbitDatabase` in `kepler-core` via the `Secrets` trait and provides an implementation of the trait based on simple per-orbit derivation from a static secret. It requires that pr #143 be merged first. It makes a breaking change in the HTTP API at `/peer/generate`, now requiring that the caller provides the ID of the Orbit being created as the final segment of the path in URL percent-encoded form. There should likewise be a PR for the kepler-sdk to accommodate this change.
=> impl host key derivation from static secret

Cargo.lock, kepler-core/src/models/delegation.rs, kepler-core/src/models/invocation.rs, kepler-core/src/models/revocation.rs
re-using a delegation/invocation/revocation should be accepted and not throw an error, except in the case of verification failing or revocation having been applied to a parent. currently kepler will have a conflict in the DB upon insertion of the row into the table. this PR sets such conflicts to not throw an error, but still applies the other verification rules, so re-use of the token will be either a verification error or a no-op.
=> fix duplicate del/inv/rev insertion

Cargo.lock, src/lib.rs, test/docker-compose.yml
Small fix for the test docker compose file, the secret and keys type must be provided as env vars.
=> test docker compose must include secrets config

Cargo.lock, kepler-core/src/db.rs, kepler-core/src/keys.rs, src/routes/mod.rs
Currently peers are represented in delegations by URIs of the form `peer:<PEER-ID>`, which is neither a proper URI or a DID. This PR adds a way to get a `did:key` DID of a peer. At the moment this is mostly an aesthetic change as we don't use peer IDs, but it's a change we should make before we start using the Peers keys to sign things
=> use did:key for peer IDs

Cargo.lock, src/auth_guards.rs, test/load/k6/json_put.js, test/load/k6/utils.js, test/load/signer/Cargo.lock, test/load/signer/Cargo.toml, test/load/signer/src/main.rs
Requests to `/peer/generate/` now have to include the orbit ID the peer will be used for in the path. This pr adds that to the load tests. It also allows for invocations without the content-type header set
=> load test update and fix

kepler-core/src/db.rs, src/lib.rs, src/routes/mod.rs
DB connection failing to be acquired from the connection pool currently results in a `401 unauthorised` status code, when it should probably be a 500 or 503 status. This PR sets it to give a 503 status in this case. not necessarily a bug fix but will be more informative in future. Additionally, this pr sets the max number of connections to 100 (previously defaulted to 10) and adds a db status check to the `/healthz` endpoint.
=> slightly improved http error status codes and db health check
